### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by harshkolhatkar** [MrWong99/gitscanner#65]
### Describe the bug
`go build .` errors out with this error 
`go build .
main.go:29:12: pattern ui/dist/search-binary/*: no matching files found`
This line seems to be embedding some files from ui/dist dir, but that directory seems to be missing from the code.
### Expected behavior
No error appears when building

**Comment by MrWong99** [comment]
Hi @harshkolhatkar, did you do a
```
cd ui
npm install
npm run build
```
before the Go build? Unfortunately with the current setup the ui needs to be build before the backend can be build since the backend includes it. You need to have node.js and npm installed too.

Maybe take a look at the current [workflow to build the code](https://github.com/MrWong99/gitscanner/blob/master/.github/workflows/build.yml#L19-L40)
